import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "@/app/components/Footer"
import { Toaster } from "react-hot-toast";
import { PlanProvider } from "@/app/context/PlanContext";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${oswald.className} h-full antialiased`}
    >
      <body>
        <PlanProvider>
        <Navbar/>
        <div className="min-h-full flex flex-col">
          {children}
          <Toaster position="top-right" />
        </div>
        <Footer/>
        </PlanProvider>
      </body>
    </html>
  );
}
